# Generated by Django 3.2 on 2024-11-10 01:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('subdistrict', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,20}$')])),
            ],
        ),
        migrations.CreateModel(
            name='TypeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_project', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('ktp_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_ktp_number', message='KTP number must be numeric.', regex='^\\d+$')])),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be numeric.', regex='^\\d+$')])),
                ('password', models.CharField(max_length=128)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('Finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.finance')),
            ],
        ),
        migrations.CreateModel(
            name='UsersProyect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=50)),
                ('location_project', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usersproyect')),
                ('type_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typeproject')),
            ],
        ),
    ]
